/* Normalized BDM v1.1 templates. Expressions are compiled to functions; no eval is used in the browser. */
'use strict';
const BdmBank=(()=>{
 const LEVEL_SUFFIX=['b1','b2','m1','m2','h1','h2'];
 const ITEMS=[
  {bank_id:"BDM-51-001",unit:"5.1",level:"초급",type:"개념 판별",template:"두 점 {A}, {B}를 양 끝점으로 하고 그 사이만 포함하는 기본 도형은?",values:{"A":["P","R","A"],"B":["Q","S","B"]},valid:null,answer:v=>{const {A,B}=v;return '선분';},wrong:[v=>{const {A,B}=v;return '직선';},v=>{const {A,B}=v;return '반직선';},v=>{const {A,B}=v;return '평면';}],explain:"양 끝점이 모두 있고 두 점 사이만 포함하므로 선분이다.",suffix:""},
  {bank_id:"BDM-51-002",unit:"5.1",level:"초급",type:"개념 판별",template:"점 {A}에서 시작하여 점 {B} 쪽으로 끝없이 뻗는 도형의 이름은?",values:{"A":["A","M","P"],"B":["B","N","Q"]},valid:null,answer:v=>{const {A,B}=v;return '반직선 '+A+B;},wrong:[v=>{const {A,B}=v;return '반직선 '+B+A;},v=>{const {A,B}=v;return '선분 '+A+B;},v=>{const {A,B}=v;return '직선 '+A+B;}],explain:"반직선은 시작점을 먼저 쓰므로 반직선 {A}{B}이다.",suffix:""},
  {bank_id:"BDM-51-003",unit:"5.1",level:"중급",type:"개수 계산",template:"서로 다른 {n}개의 점이 한 직선 위에 있다. 두 점을 양 끝점으로 하는 선분은 모두 몇 개인가?",values:{"n":[4,5,6,7,8]},valid:null,answer:v=>{const {n}=v;return n*(n-1)/2;},wrong:[v=>{const {n}=v;return n-1;},v=>{const {n}=v;return n*(n-1);},v=>{const {n}=v;return n*(n+1)/2;}],explain:"선분 하나는 서로 다른 두 점을 고르면 정해지므로 {n}C2={n}×({n}-1)÷2이다.",suffix:"개"},
  {bank_id:"BDM-51-004",unit:"5.1",level:"중급",type:"길이 계산",template:"점 {A}, {B}, {C}가 이 순서로 한 직선 위에 있고 {A}{B}={a}cm, {B}{C}={b}cm이다. {A}{C}의 길이는?",values:{"A":["A","P"],"B":["B","Q"],"C":["C","R"],"a":[3,4,5,6,7],"b":[4,6,8,9,11]},valid:null,answer:v=>{const {A,B,C,a,b}=v;return a+b;},wrong:[v=>{const {A,B,C,a,b}=v;return Math.abs(a-b);},v=>{const {A,B,C,a,b}=v;return a+b+1;},v=>{const {A,B,C,a,b}=v;return a*b;}],explain:"{B}가 {A}와 {C} 사이에 있으므로 {A}{C}={A}{B}+{B}{C}={a}+{b}이다.",suffix:" cm"},
  {bank_id:"BDM-51-005",unit:"5.1",level:"상급",type:"길이 추론",template:"선분 {A}{B}의 길이는 {L}cm이다. {M}은 {A}{B}의 중점이고, {N}은 {M}{B}의 중점이다. {A}{N}의 길이는?",values:{"A":["A","P"],"B":["B","Q"],"M":["M"],"N":["N"],"L":[12,16,20,24,28]},valid:null,answer:v=>{const {A,B,M,N,L}=v;return 3*L/4;},wrong:[v=>{const {A,B,M,N,L}=v;return L/4;},v=>{const {A,B,M,N,L}=v;return L/2;},v=>{const {A,B,M,N,L}=v;return L;}],explain:"{A}{M}={L}/2이고 {M}{N}={L}/4이므로 {A}{N}=3{L}/4이다.",suffix:" cm"},
  {bank_id:"BDM-51-006",unit:"5.1",level:"상급",type:"다단계 길이 계산",template:"점 {A}, {B}, {C}, {D}가 이 순서로 한 직선 위에 있다. {A}{B}={a}cm, {B}{C}={b}cm, {C}{D}={c}cm이고 {M}은 {A}{C}의 중점이다. {M}{D}의 길이는?",values:{"A":["A"],"B":["B"],"C":["C"],"D":["D"],"M":["M"],"a":[4,6,8],"b":[2,4,6],"c":[3,5,7]},valid:null,answer:v=>{const {A,B,C,D,M,a,b,c}=v;return (a+b)/2+c;},wrong:[v=>{const {A,B,C,D,M,a,b,c}=v;return (a+b)/2;},v=>{const {A,B,C,D,M,a,b,c}=v;return a+b+c;},v=>{const {A,B,C,D,M,a,b,c}=v;return Math.abs((a+b)/2-c);}],explain:"{M}{C}=({a}+{b})/2이고 {C}{D}={c}이므로 {M}{D}=({a}+{b})/2+{c}이다.",suffix:" cm"},
  {bank_id:"BDM-52-001",unit:"5.2",level:"초급",type:"각도 계산",template:"두 각의 합이 90°이고 한 각이 {a}°이다. 다른 각의 크기는?",values:{"a":[18,24,32,37,52,58,63]},valid:null,answer:v=>{const {a}=v;return 90-a;},wrong:[v=>{const {a}=v;return 180-a;},v=>{const {a}=v;return a;},v=>{const {a}=v;return 90+a;}],explain:"여각의 합은 90°이므로 90-{a}를 계산한다.",suffix:"°"},
  {bank_id:"BDM-52-002",unit:"5.2",level:"초급",type:"개념 판별",template:"크기가 {theta}°인 각을 예각·직각·둔각 중에서 분류하면?",values:{"theta":[105,118,127,143,165]},valid:null,answer:v=>{const {theta}=v;return '둔각';},wrong:[v=>{const {theta}=v;return '예각';},v=>{const {theta}=v;return '직각';},v=>{const {theta}=v;return '평각';}],explain:"90°보다 크고 180°보다 작은 각은 둔각이다.",suffix:""},
  {bank_id:"BDM-52-003",unit:"5.2",level:"중급",type:"각도 계산",template:"반직선 {ray}가 ∠{A}{O}{B}의 이등분선이고 ∠{A}{O}{C}={a}°이다. ∠{A}{O}{B}의 크기는?",values:{"ray":["OC"],"A":["A"],"O":["O"],"B":["B"],"C":["C"],"a":[17,23,31,38,42]},valid:null,answer:v=>{const {ray,A,O,B,C,a}=v;return 2*a;},wrong:[v=>{const {ray,A,O,B,C,a}=v;return a;},v=>{const {ray,A,O,B,C,a}=v;return 90-a;},v=>{const {ray,A,O,B,C,a}=v;return 180-2*a;}],explain:"이등분선 양쪽의 각이 같으므로 전체 각은 {a}°의 2배이다.",suffix:"°"},
  {bank_id:"BDM-52-004",unit:"5.2",level:"중급",type:"비례식 활용",template:"일직선 위에 이웃한 두 각의 크기 비가 {p}:{q}이다. 작은 각의 크기는?",values:{"p":[1,2,3],"q":[3,4,5,6]},valid:v=>{const {p,q}=v;return p<q && Number.isInteger(180*p/(p+q));},answer:v=>{const {p,q}=v;return 180*p/(p+q);},wrong:[v=>{const {p,q}=v;return 180*q/(p+q);},v=>{const {p,q}=v;return 90*p/(p+q);},v=>{const {p,q}=v;return 180-p;}],explain:"이웃한 두 각의 합은 180°이므로 작은 각은 180×{p}/({p}+{q})이다.",suffix:"°"},
  {bank_id:"BDM-52-005",unit:"5.2",level:"상급",type:"다단계 각도 계산",template:"∠{A}{O}{B}={T}°이다. {O}{C}는 이 각을 이등분하고, {O}{D}는 ∠{A}{O}{C}를 다시 이등분한다. ∠{D}{O}{C}의 크기는?",values:{"A":["A"],"O":["O"],"B":["B"],"C":["C"],"D":["D"],"T":[48,64,72,88,120,144]},valid:null,answer:v=>{const {A,O,B,C,D,T}=v;return T/4;},wrong:[v=>{const {A,O,B,C,D,T}=v;return T/2;},v=>{const {A,O,B,C,D,T}=v;return 3*T/4;},v=>{const {A,O,B,C,D,T}=v;return T/8;}],explain:"첫 이등분으로 {T}/2, 다시 이등분하므로 ∠{D}{O}{C}={T}/4이다.",suffix:"°"},
  {bank_id:"BDM-52-006",unit:"5.2",level:"상급",type:"방정식 활용",template:"한 직선 위의 세 이웃한 각의 크기 비가 {p}:{q}:{r}이다. 가장 큰 각의 크기는?",values:{"p":[1,2],"q":[2,3],"r":[3,4,5]},valid:v=>{const {p,q,r}=v;return p<q && q<r && Number.isInteger(180*r/(p+q+r));},answer:v=>{const {p,q,r}=v;return 180*r/(p+q+r);},wrong:[v=>{const {p,q,r}=v;return 180*q/(p+q+r);},v=>{const {p,q,r}=v;return 360*r/(p+q+r);},v=>{const {p,q,r}=v;return 180/(p+q+r);}],explain:"세 각의 합이 180°이므로 가장 큰 각은 180×{r}/({p}+{q}+{r})이다.",suffix:"°"},
  {bank_id:"BDM-53-001",unit:"5.3",level:"초급",type:"개념 판별",template:"공간에서 두 직선이 만나지 않고 서로 평행하지도 않을 때 두 직선은 어떤 위치 관계인가?",values:{},valid:null,answer:v=>{return '꼬인 위치';},wrong:[v=>{return '평행';},v=>{return '수직';},v=>{return '일치';}],explain:"한 평면 위에 함께 놓이지 않으면서 만나지 않는 두 직선은 꼬인 위치에 있다.",suffix:""},
  {bank_id:"BDM-53-002",unit:"5.3",level:"초급",type:"개념 판별",template:"직선 ℓ이 평면 α 위에서 한 점을 지나며 서로 교차하는 두 직선에 모두 수직일 때, ℓ과 α의 관계는?",values:{},valid:null,answer:v=>{return 'ℓ은 α에 수직이다';},wrong:[v=>{return 'ℓ은 α에 평행이다';},v=>{return 'ℓ은 α에 포함된다';},v=>{return '판단할 수 없다';}],explain:"평면 위의 서로 교차하는 두 직선에 모두 수직인 직선은 그 평면에 수직이다.",suffix:""},
  {bank_id:"BDM-53-003",unit:"5.3",level:"중급",type:"개수 계산",template:"직육면체에서 한 모서리와 평행한 다른 모서리는 몇 개인가?",values:{},valid:null,answer:v=>{return 3;},wrong:[v=>{return 2;},v=>{return 4;},v=>{return 6;}],explain:"직육면체의 12개 모서리는 같은 방향끼리 4개씩 묶이므로, 주어진 모서리를 제외하면 3개이다.",suffix:"개"},
  {bank_id:"BDM-53-004",unit:"5.3",level:"중급",type:"개수 계산",template:"직육면체의 서로 평행한 두 면의 쌍은 모두 몇 쌍인가?",values:{},valid:null,answer:v=>{return 3;},wrong:[v=>{return 2;},v=>{return 4;},v=>{return 6;}],explain:"서로 마주 보는 앞·뒤, 왼쪽·오른쪽, 위·아래 면이 각각 평행하므로 3쌍이다.",suffix:"쌍"},
  {bank_id:"BDM-53-005",unit:"5.3",level:"상급",type:"공간 위치 관계",template:"직육면체에서 한 모서리와 꼬인 위치에 있는 모서리는 몇 개인가?",values:{},valid:null,answer:v=>{return 4;},wrong:[v=>{return 3;},v=>{return 5;},v=>{return 6;}],explain:"주어진 모서리를 제외한 11개 중 만나는 모서리 4개와 평행한 모서리 3개를 빼면 꼬인 모서리는 4개이다.",suffix:"개"},
  {bank_id:"BDM-53-006",unit:"5.3",level:"상급",type:"조건 해석",template:"직선 ℓ은 평면 α에 점 P에서 수직이다. 평면 α 위의 직선 m이 P를 지나지 않을 때, ℓ과 m의 위치 관계는?",values:{},valid:null,answer:v=>{return '꼬인 위치';},wrong:[v=>{return '수직';},v=>{return '평행';},v=>{return '일치';}],explain:"ℓ과 m은 만나지 않고 같은 평면 위에 놓이지도 않으므로 꼬인 위치이다. 방향만 수직이어도 두 직선이 만나지 않으면 수직인 두 직선이라 하지 않는다.",suffix:""},
  {bank_id:"BDM-54-001",unit:"5.4",level:"초급",type:"각도 계산",template:"평행한 두 직선을 한 직선이 가로지를 때 한 엇각이 {a}°이다. 그와 짝인 엇각의 크기는?",values:{"a":[28,37,46,58,71,83]},valid:null,answer:v=>{const {a}=v;return a;},wrong:[v=>{const {a}=v;return 180-a;},v=>{const {a}=v;return 90-a;},v=>{const {a}=v;return 2*a;}],explain:"평행선에서 엇각의 크기는 서로 같으므로 {a}°이다.",suffix:"°"},
  {bank_id:"BDM-54-002",unit:"5.4",level:"초급",type:"방정식 활용",template:"두 직선을 가로지르는 횡단선에서 한 쌍의 동위각이 각각 ({m}x+{a})°와 ({n}x+{b})°이다. 두 직선이 평행하고 x={x}일 때 두 각의 크기는?",values:{"m":[2],"n":[4],"a":[14],"b":[-22],"x":[18]},valid:null,answer:v=>{const {m,n,a,b,x}=v;return m*x+a;},wrong:[v=>{const {m,n,a,b,x}=v;return n*x-b;},v=>{const {m,n,a,b,x}=v;return 180-(m*x+a);},v=>{const {m,n,a,b,x}=v;return x;}],explain:"평행선의 동위각은 같고, 주어진 x를 대입하면 {m}×{x}+{a}°이다.",suffix:"°"},
  {bank_id:"BDM-54-003",unit:"5.4",level:"중급",type:"방정식 활용",template:"평행한 두 직선 사이의 동측내각이 ({m}x+{a})°와 ({n}x+{b})°이다. x의 값은?",values:{"m":[4],"n":[2],"a":[10],"b":[20]},valid:null,answer:v=>{const {m,n,a,b}=v;return (180-a-b)/(m+n);},wrong:[v=>{const {m,n,a,b}=v;return 180/(m+n);},v=>{const {m,n,a,b}=v;return (180+a+b)/(m+n);},v=>{const {m,n,a,b}=v;return (a+b)/(m+n);}],explain:"동측내각의 합은 180°이므로 ({m}+{n})x+{a}+{b}=180을 푼다.",suffix:""},
  {bank_id:"BDM-54-004",unit:"5.4",level:"중급",type:"각도 계산",template:"평행한 두 직선 사이의 점 P에서 위쪽 선을 향한 반직선이 평행선과 {a}°, 아래쪽 선을 향한 반직선이 평행선과 {b}°를 이룬다. 두 반직선 사이의 작은 각은?",values:{"a":[18,24,31,36],"b":[27,35,42,48]},valid:null,answer:v=>{const {a,b}=v;return a+b;},wrong:[v=>{const {a,b}=v;return Math.abs(a-b);},v=>{const {a,b}=v;return 180-a-b;},v=>{const {a,b}=v;return 90-a+b;}],explain:"P를 지나는 보조 평행선을 그으면 엇각으로 {a}°와 {b}°가 옮겨져 작은 각은 {a}+{b}이다.",suffix:"°"},
  {bank_id:"BDM-54-005",unit:"5.4",level:"상급",type:"성질 증명",template:"평행한 두 직선을 한 횡단선이 가로지를 때 같은 쪽 두 내각의 이등분선이 이루는 각의 크기는?",values:{},valid:null,answer:v=>{return 90;},wrong:[v=>{return 45;},v=>{return 60;},v=>{return 180;}],explain:"같은 쪽 내각의 합은 180°이고 각각을 이등분하므로 두 이등분선 사이의 각은 180÷2=90°이다.",suffix:"°"},
  {bank_id:"BDM-54-006",unit:"5.4",level:"상급",type:"다단계 방정식",template:"평행선의 한 쌍의 동위각이 ({m}x-{a})°와 ({n}x+{b})°이다. 두 각이 같을 때, 첫 번째 각과 이웃한 각의 크기는?",values:{"m":[5],"n":[3],"a":[7],"b":[29]},valid:null,answer:v=>{const {m,n,a,b}=v;return 180-(m*((a+b)/(m-n))-a);},wrong:[v=>{const {m,n,a,b}=v;return m*((a+b)/(m-n))-a;},v=>{const {m,n,a,b}=v;return 180-((a+b)/(m-n));},v=>{const {m,n,a,b}=v;return n*((a+b)/(m-n))+b+10;}],explain:"동위각이 같으므로 ({m}-{n})x={a}+{b}에서 x를 구한다. 첫 각을 구한 뒤 일직선 위 이웃각이므로 180°에서 뺀다.",suffix:"°"},
  {bank_id:"BDM-55-001",unit:"5.5",level:"초급",type:"개념 판별",template:"삼각형을 작도할 때 컴퍼스로 직접 할 수 있는 작업은?",values:{},valid:null,answer:v=>{return '주어진 길이를 다른 위치에 옮기기';},wrong:[v=>{return '직선의 길이를 눈금으로 재기';},v=>{return '각도기로 각의 크기를 재기';},v=>{return '평행선을 눈금으로 확인하기';}],explain:"컴퍼스는 두 점 사이의 거리를 보존하여 원이나 호를 그리므로 길이를 옮길 수 있다.",suffix:""},
  {bank_id:"BDM-55-002",unit:"5.5",level:"초급",type:"작도 순서",template:"주어진 각과 크기가 같은 각을 작도할 때, 새 꼭짓점을 중심으로 먼저 그려야 하는 것은?",values:{},valid:null,answer:v=>{return '원래 각에서 그린 호와 반지름이 같은 호';},wrong:[v=>{return '임의의 길이인 선분';},v=>{return '원래 각의 이등분선';},v=>{return '두 변에 수직인 직선';}],explain:"같은 각을 옮기려면 먼저 같은 반지름의 호를 그린 뒤 호 위 두 교점 사이의 거리를 옮긴다.",suffix:""},
  {bank_id:"BDM-55-003",unit:"5.5",level:"중급",type:"작도 가능 조건",template:"세 변의 길이가 {a}cm, {b}cm, {c}cm일 때 삼각형을 작도할 수 있는가?",values:{"a":[4,5,6],"b":[6,7,8],"c":[7,8,9]},valid:v=>{const {a,b,c}=v;return a+b>c && a+c>b && b+c>a;},answer:v=>{const {a,b,c}=v;return '작도할 수 있다';},wrong:[v=>{const {a,b,c}=v;return '작도할 수 없다';},v=>{const {a,b,c}=v;return '직각삼각형만 가능하다';},v=>{const {a,b,c}=v;return '정삼각형만 가능하다';}],explain:"가장 긴 변의 길이가 나머지 두 변의 길이의 합보다 작으므로 삼각형을 작도할 수 있다.",suffix:""},
  {bank_id:"BDM-55-004",unit:"5.5",level:"중급",type:"조건 판별",template:"다음 중 삼각형 하나를 정할 수 있는 조건은?",values:{},valid:null,answer:v=>{return '한 변의 길이와 그 양 끝각의 크기';},wrong:[v=>{return '세 각의 크기';},v=>{return '두 변의 길이';},v=>{return '한 변의 길이와 그 맞은편 각 하나';}],explain:"한 변과 그 양 끝각이 주어지면 ASA 조건으로 삼각형의 모양과 크기가 하나로 정해진다.",suffix:""},
  {bank_id:"BDM-55-005",unit:"5.5",level:"상급",type:"정수 조건 계산",template:"두 변의 길이가 {a}cm, {b}cm인 삼각형의 나머지 한 변 길이가 자연수일 때 가능한 길이는 모두 몇 개인가?",values:{"a":[4,5,6,7],"b":[6,8,9,11]},valid:null,answer:v=>{const {a,b}=v;return 2*Math.min(a,b)-1;},wrong:[v=>{const {a,b}=v;return a+b;},v=>{const {a,b}=v;return Math.abs(a-b)+1;},v=>{const {a,b}=v;return 2*Math.max(a,b)+1;}],explain:"|{a}-{b}|<c<{a}+{b}를 만족하는 자연수 c의 개수는 2×min({a},{b})-1개이다.",suffix:"개"},
  {bank_id:"BDM-55-006",unit:"5.5",level:"상급",type:"작도 결과 추론",template:"선분 {A}{B}의 길이가 {c}cm이고 {A}{C}={b}cm, {B}{C}={a}cm인 삼각형을 작도한다. 점 {C}를 직선 {A}{B}의 양쪽에서 모두 허용할 때 가능한 위치는 몇 개인가?",values:{"A":["A"],"B":["B"],"C":["C"],"a":[5],"b":[6],"c":[7]},valid:null,answer:v=>{const {A,B,C,a,b,c}=v;return 2;},wrong:[v=>{const {A,B,C,a,b,c}=v;return 0;},v=>{const {A,B,C,a,b,c}=v;return 1;},v=>{const {A,B,C,a,b,c}=v;return 3;}],explain:"{A} 중심 반지름 {b}, {B} 중심 반지름 {a}인 두 원은 {A}{B}의 위아래에서 두 점에서 만나므로 가능한 {C}는 2개이다.",suffix:"개"},
  {bank_id:"BDM-56-001",unit:"5.6",level:"초급",type:"대응점 찾기",template:"△{A}{B}{C}≡△{D}{E}{F}일 때 점 {B}에 대응하는 점은?",values:{"A":["A"],"B":["B"],"C":["C"],"D":["D"],"E":["E"],"F":["F"]},valid:null,answer:v=>{const {A,B,C,D,E,F}=v;return E;},wrong:[v=>{const {A,B,C,D,E,F}=v;return D;},v=>{const {A,B,C,D,E,F}=v;return F;},v=>{const {A,B,C,D,E,F}=v;return '정할 수 없음';}],explain:"합동 기호에서 같은 순서의 꼭짓점끼리 대응하므로 두 번째 점 {B}에는 {E}가 대응한다.",suffix:""},
  {bank_id:"BDM-56-002",unit:"5.6",level:"초급",type:"합동조건 판별",template:"두 삼각형에서 세 쌍의 대응변 길이가 각각 같음을 알았다. 적용할 합동조건은?",values:{},valid:null,answer:v=>{return 'SSS 합동';},wrong:[v=>{return 'SAS 합동';},v=>{return 'ASA 합동';},v=>{return 'AAA 합동';}],explain:"세 쌍의 대응변이 각각 같으므로 SSS 합동이다.",suffix:""},
  {bank_id:"BDM-56-003",unit:"5.6",level:"중급",type:"길이 계산",template:"△{A}{B}{C}≡△{D}{E}{F}이고 {B}{C}={a}cm일 때 {E}{F}의 길이는?",values:{"A":["A"],"B":["B"],"C":["C"],"D":["D"],"E":["E"],"F":["F"],"a":[4,6,7,9,12,15]},valid:null,answer:v=>{const {A,B,C,D,E,F,a}=v;return a;},wrong:[v=>{const {A,B,C,D,E,F,a}=v;return a+2;},v=>{const {A,B,C,D,E,F,a}=v;return 2*a;},v=>{const {A,B,C,D,E,F,a}=v;return Math.max(1,a-2);}],explain:"합동 기호의 순서에서 {B}{C}와 {E}{F}가 대응하므로 길이가 같다.",suffix:" cm"},
  {bank_id:"BDM-56-004",unit:"5.6",level:"중급",type:"방정식 활용",template:"합동인 두 삼각형의 한 쌍의 대응각이 ({m}x+{a})°와 ({n}x+{b})°이다. x의 값은?",values:{"m":[2],"n":[4],"a":[18],"b":[-10]},valid:null,answer:v=>{const {m,n,a,b}=v;return (a-b)/(n-m);},wrong:[v=>{const {m,n,a,b}=v;return (a+b)/(n-m);},v=>{const {m,n,a,b}=v;return (a-b)/(n+m);},v=>{const {m,n,a,b}=v;return a-b;}],explain:"합동인 삼각형의 대응각은 같으므로 {m}x+{a}={n}x+{b}를 풀면 된다.",suffix:""},
  {bank_id:"BDM-56-005",unit:"5.6",level:"상급",type:"증명 빈칸",template:"사각형 {A}{B}{C}{D}에서 {A}{B}={A}{D}, {B}{C}={D}{C}이고 대각선 {A}{C}를 그었다. △{A}{B}{C}와 △{A}{D}{C}의 합동조건은?",values:{"A":["A"],"B":["B"],"C":["C"],"D":["D"]},valid:null,answer:v=>{const {A,B,C,D}=v;return 'SSS 합동';},wrong:[v=>{const {A,B,C,D}=v;return 'SAS 합동';},v=>{const {A,B,C,D}=v;return 'ASA 합동';},v=>{const {A,B,C,D}=v;return 'AAA 합동';}],explain:"{A}{B}={A}{D}, {B}{C}={D}{C}, {A}{C}는 공통변이므로 세 대응변이 같아 SSS 합동이다.",suffix:""},
  {bank_id:"BDM-56-006",unit:"5.6",level:"상급",type:"다단계 추론",template:"△{A}{B}{C}와 △{A}{D}{C}가 SAS 합동이다. {A}{B}={A}{D}, {A}{C}는 공통변이고 ∠{B}{A}{C}=({m}x+{a})°, ∠{C}{A}{D}=({n}x+{b})°일 때 x의 값은?",values:{"A":["A"],"B":["B"],"C":["C"],"D":["D"],"m":[3],"n":[5],"a":[12],"b":[-8]},valid:null,answer:v=>{const {A,B,C,D,m,n,a,b}=v;return (a-b)/(n-m);},wrong:[v=>{const {A,B,C,D,m,n,a,b}=v;return (a+b)/(n-m);},v=>{const {A,B,C,D,m,n,a,b}=v;return (a-b)/(n+m);},v=>{const {A,B,C,D,m,n,a,b}=v;return (n-m)/(a-b);}],explain:"SAS 합동에서 두 변 사이의 대응각이 같으므로 {m}x+{a}={n}x+{b}를 풀어 x를 구한다.",suffix:""},
  {bank_id:"BDM-61-001",unit:"6.1",level:"초급",type:"개수 계산",template:"{n}각형의 한 꼭짓점에서 그을 수 있는 대각선은 몇 개인가?",values:{"n":[5,6,7,8,9,10]},valid:null,answer:v=>{const {n}=v;return n-3;},wrong:[v=>{const {n}=v;return n-2;},v=>{const {n}=v;return n-1;},v=>{const {n}=v;return n;}],explain:"자기 자신과 양옆의 두 꼭짓점에는 대각선을 그을 수 없으므로 {n}-3개이다.",suffix:"개"},
  {bank_id:"BDM-61-002",unit:"6.1",level:"초급",type:"공식 적용",template:"{n}각형의 대각선은 모두 몇 개인가?",values:{"n":[5,6,7,8,9,10,12]},valid:null,answer:v=>{const {n}=v;return n*(n-3)/2;},wrong:[v=>{const {n}=v;return n*(n-3);},v=>{const {n}=v;return n*(n-2)/2;},v=>{const {n}=v;return (n-3)/2;}],explain:"각 꼭짓점에서 {n}-3개씩 세고 한 대각선이 두 번 세어지므로 {n}({n}-3)/2이다.",suffix:"개"},
  {bank_id:"BDM-61-003",unit:"6.1",level:"중급",type:"역으로 다각형 찾기",template:"한 꼭짓점에서 대각선을 {d}개 그을 수 있는 다각형은 몇 각형인가?",values:{"d":[2,3,4,5,6,7,8,9]},valid:null,answer:v=>{const {d}=v;return d+3;},wrong:[v=>{const {d}=v;return d+1;},v=>{const {d}=v;return d+2;},v=>{const {d}=v;return d+4;}],explain:"n-3={d}이므로 n={d}+3이다.",suffix:"각형"},
  {bank_id:"BDM-61-004",unit:"6.1",level:"중급",type:"개수 계산",template:"볼록 {n}각형의 한 꼭짓점에서 모든 대각선을 그으면 내부는 몇 개의 삼각형으로 나뉘는가?",values:{"n":[5,6,7,8,9,10]},valid:null,answer:v=>{const {n}=v;return n-2;},wrong:[v=>{const {n}=v;return n-3;},v=>{const {n}=v;return n-1;},v=>{const {n}=v;return 2*n-4;}],explain:"한 꼭짓점에서 그은 대각선은 다각형을 {n}-2개의 삼각형으로 나눈다.",suffix:"개"},
  {bank_id:"BDM-61-005",unit:"6.1",level:"상급",type:"역으로 다각형 찾기",template:"대각선의 총수가 {D}개인 다각형은 몇 각형인가?",values:{"D":[9,14,20,27,35,44,54]},valid:null,answer:v=>{const {D}=v;return ({9:6,14:7,20:8,27:9,35:10,44:11,54:12})[D];},wrong:[v=>{const {D}=v;return ({9:5,14:6,20:7,27:8,35:9,44:10,54:11})[D];},v=>{const {D}=v;return D-2;},v=>{const {D}=v;return Math.round(Math.sqrt(2*D));}],explain:"n(n-3)/2={D}를 만족하는 자연수 n을 찾는다.",suffix:"각형"},
  {bank_id:"BDM-61-006",unit:"6.1",level:"상급",type:"식의 활용",template:"{n}각형보다 꼭짓점이 하나 많은 다각형의 대각선 수는 {n}각형보다 몇 개 더 많은가?",values:{"n":[5,6,7,8,9,10]},valid:null,answer:v=>{const {n}=v;return n-1;},wrong:[v=>{const {n}=v;return n-2;},v=>{const {n}=v;return n;},v=>{const {n}=v;return 2*n-3;}],explain:"(n+1)(n-2)/2-n(n-3)/2를 정리하면 n-1이다.",suffix:"개"},
  {bank_id:"BDM-62-001",unit:"6.2",level:"초급",type:"각도 계산",template:"삼각형의 두 내각이 {a}°, {b}°일 때 나머지 한 내각의 크기는?",values:{"a":[35,42,48,55,63],"b":[47,58,66,72,81]},valid:v=>{const {a,b}=v;return a+b<180;},answer:v=>{const {a,b}=v;return 180-a-b;},wrong:[v=>{const {a,b}=v;return a+b;},v=>{const {a,b}=v;return 180-a;},v=>{const {a,b}=v;return 90-b;}],explain:"삼각형의 세 내각의 합은 180°이므로 180-{a}-{b}이다.",suffix:"°"},
  {bank_id:"BDM-62-002",unit:"6.2",level:"초급",type:"각도 계산",template:"삼각형의 한 외각과 이웃하지 않는 두 내각이 {a}°, {b}°이다. 그 외각의 크기는?",values:{"a":[31,38,45,52],"b":[47,56,63,71]},valid:null,answer:v=>{const {a,b}=v;return a+b;},wrong:[v=>{const {a,b}=v;return 180-a-b;},v=>{const {a,b}=v;return Math.abs(a-b);},v=>{const {a,b}=v;return 180-a;}],explain:"삼각형의 한 외각은 이웃하지 않는 두 내각의 합과 같으므로 {a}+{b}이다.",suffix:"°"},
  {bank_id:"BDM-62-003",unit:"6.2",level:"중급",type:"각도 계산",template:"이등변삼각형에서 꼭지각의 외각이 {e}°이다. 두 밑각 중 하나의 크기는?",values:{"e":[100,110,130,140,150]},valid:null,answer:v=>{const {e}=v;return e/2;},wrong:[v=>{const {e}=v;return 180-e;},v=>{const {e}=v;return (180-e)/2;},v=>{const {e}=v;return e;}],explain:"꼭지각을 제외한 두 밑각의 합이 외각 {e}°와 같고 두 밑각이 같으므로 각각 {e}/2°이다.",suffix:"°"},
  {bank_id:"BDM-62-004",unit:"6.2",level:"중급",type:"방정식 활용",template:"삼각형의 세 내각이 ({p}x)°, ({q}x)°, ({r}x)°일 때 x의 값은?",values:{"p":[2],"q":[3],"r":[4]},valid:null,answer:v=>{const {p,q,r}=v;return 180/(p+q+r);},wrong:[v=>{const {p,q,r}=v;return 180/(p+q);},v=>{const {p,q,r}=v;return 360/(p+q+r);},v=>{const {p,q,r}=v;return p+q+r;}],explain:"세 내각의 합이 180°이므로 ({p}+{q}+{r})x=180이다.",suffix:""},
  {bank_id:"BDM-62-005",unit:"6.2",level:"상급",type:"다단계 각도 계산",template:"△ABC에서 변 BC를 C 쪽으로 연장한 외각이 {e}°이고 ∠A:∠B={p}:{q}이다. ∠A의 크기는?",values:{"e":[90,105,120,135,150],"p":[1,2,3],"q":[2,3,4]},valid:v=>{const {e,p,q}=v;return p<q && e*p/(p+q)>0 && Number.isInteger(e*p/(p+q));},answer:v=>{const {e,p,q}=v;return e*p/(p+q);},wrong:[v=>{const {e,p,q}=v;return e*q/(p+q);},v=>{const {e,p,q}=v;return 180;},v=>{const {e,p,q}=v;return e+10;}],explain:"외각 {e}°는 ∠A+∠B이고 두 각의 비가 {p}:{q}이므로 ∠A={e}×{p}/({p}+{q})이다.",suffix:"°"},
  {bank_id:"BDM-62-006",unit:"6.2",level:"상급",type:"성질 추론",template:"삼각형의 각 꼭짓점에서 한 변을 같은 방향으로 연장해 얻은 세 외각 중 두 각이 {a}°, {b}°이다. 나머지 외각은?",values:{"a":[95,110,125],"b":[105,120,135]},valid:v=>{const {a,b}=v;return a+b<360 && 360-a-b<180;},answer:v=>{const {a,b}=v;return 360-a-b;},wrong:[v=>{const {a,b}=v;return 180-a-b;},v=>{const {a,b}=v;return a+b;},v=>{const {a,b}=v;return 180-Math.abs(a-b);}],explain:"다각형의 외각의 합은 삼각형에서도 360°이므로 360-{a}-{b}이다.",suffix:"°"},
  {bank_id:"BDM-63-001",unit:"6.3",level:"초급",type:"공식 적용",template:"{n}각형의 내각의 크기의 합은?",values:{"n":[5,6,7,8,9,10,12]},valid:null,answer:v=>{const {n}=v;return (n-2)*180;},wrong:[v=>{const {n}=v;return (n-3)*180;},v=>{const {n}=v;return n*180;},v=>{const {n}=v;return (n-2)*360;}],explain:"{n}각형은 한 꼭짓점에서 {n}-2개의 삼각형으로 나뉘므로 내각의 합은 ({n}-2)×180°이다.",suffix:"°"},
  {bank_id:"BDM-63-002",unit:"6.3",level:"초급",type:"각도 계산",template:"정{n}각형의 한 내각의 크기는?",values:{"n":[5,6,8,9,10,12]},valid:null,answer:v=>{const {n}=v;return (n-2)*180/n;},wrong:[v=>{const {n}=v;return 360/n;},v=>{const {n}=v;return (n-2)*180;},v=>{const {n}=v;return 180/n;}],explain:"정{n}각형의 내각은 모두 같으므로 내각의 합 ({n}-2)×180°를 {n}으로 나눈다.",suffix:"°"},
  {bank_id:"BDM-63-003",unit:"6.3",level:"중급",type:"역으로 다각형 찾기",template:"내각의 크기의 합이 {S}°인 다각형은 몇 각형인가?",values:{"S":[540,720,900,1080,1260,1440]},valid:null,answer:v=>{const {S}=v;return S/180+2;},wrong:[v=>{const {S}=v;return S/180;},v=>{const {S}=v;return S/180+1;},v=>{const {S}=v;return S/180+3;}],explain:"(n-2)×180={S}이므로 n={S}/180+2이다.",suffix:"각형"},
  {bank_id:"BDM-63-004",unit:"6.3",level:"중급",type:"각도 계산",template:"볼록 {n}각형의 내각 중 한 각을 제외한 합이 {partial}°이다. 빠진 한 내각의 크기는?",values:{"n":[5,6,7],"partial":[430,590,760]},valid:v=>{const {n,partial}=v;return (n-2)*180-partial>0 && (n-2)*180-partial<180;},answer:v=>{const {n,partial}=v;return (n-2)*180-partial;},wrong:[v=>{const {n,partial}=v;return partial-(n-3)*180;},v=>{const {n,partial}=v;return 180-partial;},v=>{const {n,partial}=v;return (n-1)*180-partial;}],explain:"전체 내각의 합 ({n}-2)×180°에서 알려진 각들의 합 {partial}°를 뺀다.",suffix:"°"},
  {bank_id:"BDM-63-005",unit:"6.3",level:"상급",type:"방정식 활용",template:"정다각형의 한 내각이 {I}°일 때 이 다각형의 변의 수는?",values:{"I":[108,120,135,140,144,150]},valid:null,answer:v=>{const {I}=v;return 360/(180-I);},wrong:[v=>{const {I}=v;return 180/(180-I);},v=>{const {I}=v;return 180/I;},v=>{const {I}=v;return I/10;}],explain:"한 외각은 180-{I}°이고 정다각형의 외각의 합은 360°이므로 변의 수는 360/(180-{I})이다.",suffix:"각형"},
  {bank_id:"BDM-63-006",unit:"6.3",level:"상급",type:"식의 활용",template:"{n}각형의 내각의 합은 {m}각형의 내각의 합보다 몇 도 큰가?",values:{"n":[8,9,10,12],"m":[5,6,7]},valid:v=>{const {n,m}=v;return n>m;},answer:v=>{const {n,m}=v;return (n-m)*180;},wrong:[v=>{const {n,m}=v;return (n-m-2)*180;},v=>{const {n,m}=v;return (n-m)*360;},v=>{const {n,m}=v;return (n+m-4)*180;}],explain:"두 내각 합의 차는 [(n-2)-(m-2)]×180=(n-m)×180°이다.",suffix:"°"},
  {bank_id:"BDM-64-001",unit:"6.4",level:"초급",type:"성질 확인",template:"볼록다각형의 각 꼭짓점에서 같은 방향으로 하나씩 잡은 외각의 크기의 합은?",values:{},valid:null,answer:v=>{return 360;},wrong:[v=>{return 180;},v=>{return 540;},v=>{return '다각형에 따라 다름';}],explain:"다각형 둘레를 한 바퀴 돌 때 진행 방향이 총 한 바퀴, 즉 360° 회전한다.",suffix:"°"},
  {bank_id:"BDM-64-002",unit:"6.4",level:"초급",type:"각도 계산",template:"정{n}각형의 한 외각의 크기는?",values:{"n":[5,6,8,9,10,12]},valid:null,answer:v=>{const {n}=v;return 360/n;},wrong:[v=>{const {n}=v;return 180/n;},v=>{const {n}=v;return (n-2)*180/n;},v=>{const {n}=v;return 360/(n-1);}],explain:"정다각형의 외각은 모두 같고 합이 360°이므로 360÷{n}이다.",suffix:"°"},
  {bank_id:"BDM-64-003",unit:"6.4",level:"중급",type:"역으로 다각형 찾기",template:"한 외각의 크기가 {E}°인 정다각형은 몇 각형인가?",values:{"E":[24,30,36,40,45,60,72]},valid:null,answer:v=>{const {E}=v;return 360/E;},wrong:[v=>{const {E}=v;return 180/E;},v=>{const {E}=v;return 360/E+2;},v=>{const {E}=v;return 180-360/E;}],explain:"정다각형의 외각의 합이 360°이므로 변의 수는 360÷{E}이다.",suffix:"각형"},
  {bank_id:"BDM-64-004",unit:"6.4",level:"중급",type:"각도 계산",template:"볼록 {n}각형의 외각 중 한 각을 제외한 합이 {partial}°이다. 빠진 외각의 크기는?",values:{"n":[5,6,7,8],"partial":[245,260,275,290,305]},valid:null,answer:v=>{const {n,partial}=v;return 360-partial;},wrong:[v=>{const {n,partial}=v;return 180-partial;},v=>{const {n,partial}=v;return partial-(n-2)*180;},v=>{const {n,partial}=v;return 360/n;}],explain:"변의 수와 관계없이 외각의 합은 360°이므로 360-{partial}이다.",suffix:"°"},
  {bank_id:"BDM-64-005",unit:"6.4",level:"상급",type:"비례 추론",template:"정다각형의 한 내각과 한 외각의 크기 비가 {p}:{q}이다. 이 정다각형은 몇 각형인가?",values:{"p":[2,3,4,5],"q":[1]},valid:null,answer:v=>{const {p,q}=v;return 2*(p+q)/q;},wrong:[v=>{const {p,q}=v;return 2*p/q;},v=>{const {p,q}=v;return (p+q)/q;},v=>{const {p,q}=v;return 360/(p+q);}],explain:"내각과 외각의 합은 180°이다. 외각은 180×{q}/({p}+{q})°이고 변의 수는 360을 이 값으로 나눈 2({p}+{q})/{q}이다.",suffix:"각형"},
  {bank_id:"BDM-64-006",unit:"6.4",level:"상급",type:"방정식 활용",template:"볼록 오각형의 다섯 외각이 차례로 x°, (x+{d})°, (x+{d2})°, (x+{d3})°, (x+{d4})°이다. x의 값은?",values:{"d":[10],"d2":[20],"d3":[30],"d4":[40]},valid:null,answer:v=>{const {d,d2,d3,d4}=v;return (360-d-d2-d3-d4)/5;},wrong:[v=>{const {d,d2,d3,d4}=v;return 360/5;},v=>{const {d,d2,d3,d4}=v;return (180-d-d2-d3-d4)/5;},v=>{const {d,d2,d3,d4}=v;return (360+d+d2+d3+d4)/5;}],explain:"외각의 합은 360°이므로 5x+{d}+{d2}+{d3}+{d4}=360을 푼다.",suffix:""}
 ];
 const LARGE_ANGLE=new Set(['BDM-63-001','BDM-63-006','BDM-64-001']);
 const hash=s=>{let h=2166136261;for(const c of s){h^=c.codePointAt(0);h=Math.imul(h,16777619);}return h>>>0;};
 const slotOf=item=>item.unit.replace('.','')+LEVEL_SUFFIX[(Number(item.bank_id.slice(-3))-1)%6];
 const SLOT_BY_BANK_ID=Object.fromEntries(ITEMS.map(item=>[item.bank_id,slotOf(item)]));
 const BANK_ID_BY_SLOT=Object.fromEntries(ITEMS.map(item=>[slotOf(item),item.bank_id]));
 function combinations(item){
  let out=[{}];
  for(const [name,values] of Object.entries(item.values))out=out.flatMap(v=>values.map(value=>({...v,[name]:value})));
  return item.valid?out.filter(item.valid):out;
 }
 for(const item of ITEMS)item.combinations=combinations(item);
 function text(template,v){
  return String(template).replace(/\{([A-Za-z][A-Za-z0-9]*)\}/g,(_,key)=>v[key])
   .replace(/\+\-/g,'−').replace(/([0-9A-Za-z)])-([0-9A-Za-z(])/g,'$1−$2');
 }
 const number=x=>Math.round(Number(x)*1000)/1000;
 function validChoice(item,x){
  if(typeof x==='string')return x.length>0;
  if(!Number.isFinite(x))return false;
  if(item.suffix==='개'||item.suffix==='쌍')return Number.isInteger(x)&&x>0;
  if(item.suffix==='각형')return Number.isInteger(x)&&x>=3;
  if(item.suffix===' cm')return x>0;
  if(item.suffix==='°')return x>0&&(LARGE_ANGLE.has(item.bank_id)||x<=180);
  return x>0;
 }
 const display=(item,x)=>typeof x==='number'?number(x)+item.suffix:String(x);
 function choices(item,v,answer){
  const raw=item.wrong.map(make=>make(v)),out=[];
  for(const value of raw)if(validChoice(item,value)&&display(item,value)!==answer&&!out.includes(display(item,value)))out.push(display(item,value));
  if(out.length<3&&typeof item.answer(v)==='number'){
   const a=number(item.answer(v)),steps=item.suffix==='°'?[10,-10,20,-20,30,-30]:[1,-1,2,-2,3,-3,5,-5];
   for(const step of steps){const value=a+step;if(validChoice(item,value)&&display(item,value)!==answer&&!out.includes(display(item,value)))out.push(display(item,value));if(out.length===3)break;}
  }
  if(out.length!==3)throw Error('Could not normalize choices '+item.bank_id);
  return out;
 }
 function figure(item,v){
  switch(item.bank_id){
   case 'BDM-51-005':return {kind:'bdm-line-points',names:[v.A,v.M,v.N,v.B],positions:[0,v.L/2,3*v.L/4,v.L],labels:[[0,3,v.L+' cm'],[0,2,'x cm']]};
   case 'BDM-51-006':return {kind:'bdm-line-points',names:[v.A,v.B,v.M,v.C,v.D],positions:[0,v.a,(v.a+v.b)/2,v.a+v.b,v.a+v.b+v.c],labels:[[0,1,v.a+' cm'],[1,3,v.b+' cm'],[3,4,v.c+' cm'],[2,4,'x cm']]};
   case 'BDM-52-003':return {kind:'bisect',angle:2*v.a};
   case 'BDM-52-004':return {kind:'supplement',angle:180*v.p/(v.p+v.q),labels:[v.p+'부분',v.q+'부분']};
   case 'BDM-52-005':return {kind:'bdm-nested-bisect',angle:v.T};
   case 'BDM-52-006':return {kind:'bdm-triple-angle',ratio:[v.p,v.q,v.r]};
   case 'BDM-53-002':return {kind:'bdm-plane-normal',skew:false};
   case 'BDM-53-003':return {kind:'cube',names:Array.from('ABCDEFGH'),edges:['AB']};
   case 'BDM-53-004':return {kind:'cube',names:Array.from('ABCDEFGH'),edges:[]};
   case 'BDM-53-005':return {kind:'cube',names:Array.from('ABCDEFGH'),edges:['AB']};
   case 'BDM-53-006':return {kind:'bdm-plane-normal',skew:true};
   case 'BDM-54-001':return {kind:'parallels',angle:v.a,mode:'alternate',labels:[v.a+'°','x°']};
   case 'BDM-54-002':return {kind:'parallels',angle:item.answer(v),mode:'correspond',labels:['('+v.m+'x+'+v.a+')°','('+v.n+'x'+(v.b<0?'−':'+'+v.b)+')°']};
   case 'BDM-54-003':return {kind:'parallels',angle:v.m*item.answer(v)+v.a,mode:'sameinside',labels:['('+v.m+'x+'+v.a+')°','('+v.n+'x+'+v.b+')°']};
   case 'BDM-54-004':return {kind:'bdm-between-parallels',angles:[v.a,v.b]};
   case 'BDM-54-005':return {kind:'bdm-parallel-bisectors'};
   case 'BDM-54-006':return {kind:'bdm-parallels-adjacent',angle:v.m*((v.a+v.b)/(v.m-v.n))-v.a,labels:['('+v.m+'x−'+v.a+')°','?']};
   case 'BDM-55-002':return {kind:'bdm-angle-copy'};
   case 'BDM-55-006':return {kind:'bdm-circle-intersections',sides:[v.a,v.b,v.c]};
   case 'BDM-56-003':return {kind:'pair',mode:'length',names:[v.A,v.B,v.C,v.D,v.E,v.F],sides:[v.a+1,v.a,v.a+2]};
   case 'BDM-56-005':return {kind:'bdm-kite',names:[v.A,v.B,v.C,v.D]};
   case 'BDM-56-006':return {kind:'bdm-common-side',names:[v.A,v.B,v.C,v.D],labels:['('+v.m+'x+'+v.a+')°','('+v.n+'x'+(v.b<0?'−':'+'+v.b)+')°']};
   case 'BDM-61-004':return {kind:'bdm-polygon-fan',n:v.n};
   case 'BDM-62-002':{const c=180-v.a-v.b;return {kind:'triangle-angles',angles:[v.a,v.b,c],labels:[v.a+'°',v.b+'°',''],exterior:(v.a+v.b)+'°'};}
   case 'BDM-62-003':return {kind:'triangle-angles',angles:[v.e/2,v.e/2,180-v.e],labels:['x°','x°',''],exterior:v.e+'°'};
   case 'BDM-62-005':{const a=item.answer(v),b=v.e-a;return {kind:'triangle-angles',angles:[a,b,180-v.e],labels:['x°',b+'°',''],exterior:v.e+'°'};}
   case 'BDM-62-006':return {kind:'bdm-three-exteriors',angles:[v.a,v.b,item.answer(v)]};
   default:return null;
  }
 }
 function makeCase(item,v,date,offset=0){
  const id=slotOf(item),raw=item.answer(v);
  if(!validChoice(item,raw))throw Error('Invalid answer '+item.bank_id);
  const answer=display(item,raw);
  return {id,uid:'10|'+date+'|'+id+(offset?'|r'+offset:''),date,unit:item.unit,level:item.level,type:item.type,q:text(item.template,v),a:answer,o:choices(item,v,answer),e:text(item.explain,v),fig:figure(item,v),check:null,source:'bdm',bank_id:item.bank_id};
 }
 function make(date,offset=0){
  const virtual=Math.floor(Date.parse(date+'T00:00:00Z')/86400000)+offset;
  return ITEMS.map(item=>{const variants=item.combinations;return makeCase(item,variants[hash(virtual+'|'+item.bank_id)%variants.length],date,offset);});
 }
 function allCases(date='2026-09-10'){
  return ITEMS.flatMap(item=>item.combinations.map(v=>makeCase(item,v,date,0)));
 }
 return {VERSION:'1.1',ITEMS,SLOT_BY_BANK_ID,BANK_ID_BY_SLOT,make,allCases,combinationCount:ITEMS.reduce((n,item)=>n+item.combinations.length,0)};
})();



