/* Name gate + shared daily/monthly leaderboard. math-v10 records remain unchanged. */
'use strict';
(()=>{
 const KEY='study-math-leaderboard-v1';
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
 const empty=()=>({version:1,activeName:'',players:{}});
 const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));return x&&typeof x==='object'?x:empty();}catch{return empty();}};
 let db=read();if(!db.players||typeof db.players!=='object')db.players={};if(typeof db.activeName!=='string')db.activeName='';
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(db));}catch{}};
 const today=()=>window.DailyMath?.dateKey?.()||new Date(Date.now()+9*3600000).toISOString().slice(0,10);
 const month=()=>today().slice(0,7);
 const normalizeName=s=>String(s||'').trim().replace(/\s+/g,' ');
 const validName=s=>/^[가-힣A-Za-z ]{2,20}$/u.test(s);
 function player(name=db.activeName){if(!name)return null;if(!db.players[name])db.players[name]={createdAt:Date.now(),events:{},imported:false};if(!db.players[name].events)db.players[name].events={};return db.players[name];}
 function ensureStyle(){if(document.getElementById('leaderboard-style'))return;const style=document.createElement('style');style.id='leaderboard-style';style.textContent=`
 .leader-locked{overflow:hidden}.leader-gate{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:22px;background:rgba(18,35,48,.62);backdrop-filter:blur(7px)}.leader-panel{width:min(460px,100%);background:#fff;border:1px solid #dbe4ea;border-radius:24px;padding:26px;box-shadow:0 24px 80px rgba(18,35,48,.28)}.leader-panel h2{margin:4px 0 8px;font-size:28px}.leader-panel p{margin:0 0 18px;color:#5d6d79}.leader-note{font-weight:800;color:#173f5f!important}.leader-form{display:grid;gap:10px}.leader-form label{font-weight:800}.leader-form input{width:100%;min-height:48px;padding:11px 13px;border:1px solid #bccbd5;border-radius:12px;font:inherit;font-size:16px}.leader-form input:focus{outline:3px solid rgba(47,127,212,.16);border-color:#2f7fd4}.leader-error{min-height:20px;margin:0!important;color:#b23c3c!important;font-size:13px}.leader-primary,.leader-secondary,.leader-pill,.leader-tab{border:0;border-radius:12px;font:inherit;font-weight:800;cursor:pointer}.leader-primary{min-height:48px;background:#173f5f;color:#fff}.leader-secondary{min-height:42px;padding:0 14px;background:#eef3f6;color:#173f5f}.leader-pill{margin-left:auto;padding:8px 12px;background:#eef3f6;color:#173f5f;font-size:13px}.leader-dialog{width:min(720px,calc(100% - 28px));border:0;border-radius:22px;padding:0;box-shadow:0 24px 90px rgba(18,35,48,.3)}.leader-dialog::backdrop{background:rgba(18,35,48,.55)}.leader-dialog-inner{padding:22px}.leader-head{display:flex;align-items:flex-start;gap:12px}.leader-head h2{margin:0;font-size:27px}.leader-head p{margin:3px 0 0;color:#697986}.leader-close{margin-left:auto}.leader-tabs{display:flex;gap:8px;margin:20px 0 14px}.leader-tab{padding:9px 15px;background:#eef3f6;color:#50616e}.leader-tab.on{background:#173f5f;color:#fff}.leader-table-wrap{overflow:auto;border:1px solid #dfe7ec;border-radius:14px}.leader-table{width:100%;border-collapse:collapse;min-width:470px}.leader-table th,.leader-table td{padding:12px 10px;border-bottom:1px solid #e7edf1;text-align:center}.leader-table th:nth-child(2),.leader-table td:nth-child(2){text-align:left}.leader-table tr:last-child td{border-bottom:0}.leader-rank{font-weight:900;color:#173f5f}.leader-empty{padding:28px;text-align:center;color:#697986}.leader-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:14px;color:#697986;font-size:12px}.leader-who{font-weight:800;color:#173f5f}.leader-mini{display:flex;gap:8px;align-items:center}.leader-pending{padding:10px 12px;border-radius:12px;background:#fff8de;color:#745b00;font-size:12px;margin-top:12px}
 @media(max-width:620px){.leader-panel{padding:22px 18px}.leader-dialog-inner{padding:18px}.leader-head h2{font-size:24px}.leader-pill{font-size:12px;padding:7px 10px}}
 `;document.head.appendChild(style);}
 function importExisting(name=db.activeName){const p=player(name);if(!p||p.imported)return;try{const math=JSON.parse(localStorage.getItem('math-v10')||'{}');for(const [uid,r] of Object.entries(math.history||{})){if(!r?.question||!r.date||p.events[uid])continue;p.events[uid]={uid,date:r.date,month:String(r.date).slice(0,7),correct:r.choice===r.question.a,answeredAt:Date.now(),source:r.question.source||'legacy'};}p.imported=true;save();}catch{}}
 function showGate(){ensureStyle();if(document.getElementById('leader-name-gate'))return;document.body.classList.add('leader-locked');const gate=document.createElement('div');gate.id='leader-name-gate';gate.className='leader-gate';gate.innerHTML=`<section class="leader-panel" role="dialog" aria-modal="true" aria-labelledby="leader-name-title"><p class="overline">학습부 수학</p><h2 id="leader-name-title">학습을 시작할게요</h2><p class="leader-note">이름은 본명으로 입력해주세요.</p><p>입력한 이름은 학습 기록과 리더보드에 사용됩니다.</p><form class="leader-form" id="leader-name-form"><label for="leader-name-input">이름</label><input id="leader-name-input" name="name" maxlength="20" autocomplete="name" placeholder="예: 홍길동" required><p class="leader-error" id="leader-name-error" aria-live="polite"></p><button class="leader-primary" type="submit">시작하기</button></form></section>`;document.body.appendChild(gate);const input=gate.querySelector('input');setTimeout(()=>input.focus(),0);gate.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const name=normalizeName(input.value),err=gate.querySelector('#leader-name-error');if(!validName(name)){err.textContent='한글 또는 영문 이름을 2~20자로 입력해주세요.';return;}db.activeName=name;player(name);save();importExisting(name);window.StudyLeaderboardRemote?.syncAll?.(name).catch?.(()=>{});gate.remove();document.body.classList.remove('leader-locked');installButton();});}
 function installButton(){ensureStyle();const mast=document.querySelector('.masthead');if(!mast||document.getElementById('leaderboard-button'))return;const b=document.createElement('button');b.id='leaderboard-button';b.className='leader-pill';b.type='button';b.textContent=(db.activeName?db.activeName+' · ':'')+'리더보드';b.addEventListener('click',()=>openBoard('daily'));mast.appendChild(b);}
 function localRows(mode){const target=mode==='daily'?today():month();return Object.entries(db.players).map(([name,p])=>{const ev=Object.values(p.events||{}).filter(x=>(mode==='daily'?x.date:x.month)===target);const solved=ev.length,correct=ev.filter(x=>x.correct).length,accuracy=solved?Math.round(correct/solved*100):0;return {name,solved,correct,accuracy};}).filter(x=>x.solved>0).sort((a,b)=>b.solved-a.solved||b.correct-a.correct||b.accuracy-a.accuracy||a.name.localeCompare(b.name,'ko'));}
 function rowsHtml(rows){if(!rows.length)return '<div class="leader-empty">아직 기록이 없습니다.</div>';return `<div class="leader-table-wrap"><table class="leader-table"><thead><tr><th>순위</th><th>이름</th><th>푼 문제</th><th>정답</th><th>정답률</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="leader-rank">${r.rank??i+1}</td><td>${E(r.name)}</td><td>${r.solved}</td><td>${r.correct}</td><td>${r.accuracy}%</td></tr>`).join('')}</tbody></table></div>`;}
 async function getRows(mode){const remote=window.StudyLeaderboardRemote;if(remote&&typeof remote.fetch==='function'){try{const rows=await remote.fetch(mode,mode==='daily'?today():month());if(Array.isArray(rows))return {rows,remote:true};}catch(e){console.warn('Shared leaderboard fetch failed',e);}}return {rows:localRows(mode),remote:false};}
 async function renderBoard(dialog,mode){dialog.dataset.mode=mode;dialog.querySelectorAll('.leader-tab').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));const body=dialog.querySelector('[data-board-body]');body.innerHTML='<div class="leader-empty">순위를 불러오는 중입니다.</div>';const {rows,remote}=await getRows(mode);body.innerHTML=rowsHtml(rows);const pending=dialog.querySelector('.leader-pending');pending.hidden=remote;}
 function openBoard(mode='daily'){ensureStyle();let d=document.getElementById('leaderboard-dialog');if(!d){d=document.createElement('dialog');d.id='leaderboard-dialog';d.className='leader-dialog';d.innerHTML=`<div class="leader-dialog-inner"><div class="leader-head"><div><p class="overline">학습부 수학</p><h2>리더보드</h2><p>푼 문제 수를 기준으로 순위를 보여줍니다.</p></div><button class="leader-secondary leader-close" type="button">닫기</button></div><div class="leader-tabs"><button class="leader-tab on" data-mode="daily" type="button">일간</button><button class="leader-tab" data-mode="monthly" type="button">월간</button></div><div data-board-body></div><div class="leader-pending">공용 리더보드를 불러오지 못해 이 기기의 기록만 표시 중입니다.</div><div class="leader-foot"><span class="leader-who"></span><div class="leader-mini"><button class="leader-secondary" data-change-name type="button">이름 변경</button></div></div></div>`;document.body.appendChild(d);d.querySelector('.leader-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close();});d.querySelectorAll('.leader-tab').forEach(b=>b.addEventListener('click',()=>renderBoard(d,b.dataset.mode)));d.querySelector('[data-change-name]').addEventListener('click',()=>{d.close();db.activeName='';save();document.getElementById('leaderboard-button')?.remove();showGate();});}
 d.querySelector('.leader-who').textContent='현재 이름: '+(db.activeName||'미입력');renderBoard(d,mode);d.showModal();}
 async function submitRemote(event){const remote=window.StudyLeaderboardRemote;if(remote&&typeof remote.submit==='function'){try{await remote.submit({name:db.activeName,...event});}catch(e){console.warn('Shared leaderboard submit failed',e);}}}
 function record(uid){if(!db.activeName||!uid||document.body.dataset.view==='review')return;const p=player();if(p.events[uid])return;try{const math=JSON.parse(localStorage.getItem('math-v10')||'{}'),r=math.history?.[uid];if(!r?.question||!r.date)return;const event={uid,date:r.date,month:String(r.date).slice(0,7),correct:r.choice===r.question.a,answeredAt:Date.now(),source:r.question.source||'v10'};p.events[uid]=event;save();submitRemote(event);}catch{}}
 document.addEventListener('click',e=>{const opt=e.target.closest?.('.opt[data-uid]');if(opt)setTimeout(()=>record(opt.dataset.uid),0);});
 window.addEventListener('pageshow',()=>{if(db.activeName){importExisting();window.StudyLeaderboardRemote?.syncAll?.(db.activeName).catch?.(()=>{});installButton();}else showGate();});
 ensureStyle();if(db.activeName){importExisting();window.StudyLeaderboardRemote?.syncAll?.(db.activeName).catch?.(()=>{});installButton();}else showGate();
 window.StudyLeaderboard={key:KEY,open:openBoard,getLocalData:()=>JSON.parse(JSON.stringify(db))};
})();
